//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_school.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Engineer
    {
        public int EnginnerID { get; set; }
        public int TabNumber { get; set; }
        public Nullable<int> EnSpecID { get; set; }
    
        public virtual EnSpec EnSpec { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
