//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace new_school.Components
{
    using System;
    using System.Collections.Generic;
    
    public partial class Exam
    {
        public int ExamID { get; set; }
        public Nullable<System.DateTime> Date { get; set; }
        public Nullable<int> Dis_Code { get; set; }
        public Nullable<int> RegNumber { get; set; }
        public Nullable<int> TabNumber { get; set; }
        public string Grade { get; set; }
        public Nullable<int> Auditorium { get; set; }
    
        public virtual Discipline Discipline { get; set; }
        public virtual Student Student { get; set; }
        public virtual Employee Employee { get; set; }
    }
}
