//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Pablo_school.Res
{
    using System;
    using System.Collections.Generic;
    
    public partial class Academics
    {
        public int ID { get; set; }
        public string FIO { get; set; }
        public Nullable<System.DateTime> Birthdate { get; set; }
        public string Specialization { get; set; }
        public Nullable<int> Year_invocation { get; set; }
    }
}
